import numpy as np

def get_targets() -> list[tuple[int, str]]:
    """Get the possible capture targets from the underlying os. This includes all avaliable monitors and application windows."""
    ...

class Action: ...

class Environment:
    def __init__(self) -> None: ...
    def step(self, Action) -> tuple[np.ndarray, ...]: ...
    def reset(self) -> tuple[np.ndarray, dict]: ...
    def close(self) -> None: ...
